defaults:
  - _self_
  - model: gvhmr/gvhmr_pl_demo
  - network: gvhmr/relative_transformer
  - endecoder: gvhmr/v1_amass_local_bedlam_cam

pipeline:
  _target_: hmr4d.model.gvhmr.pipeline.gvhmr_pipeline.Pipeline
  args_denoiser3d: ${network}
  args:
    endecoder_opt: ${endecoder}
    normalize_cam_angvel: True
    weights: null
    static_conf: null

ckpt_path: inputs/checkpoints/gvhmr/gvhmr_siga24_release.ckpt

# ================================ #
#          global setting          #
# ================================ #

video_name: ???
output_root: outputs/demo
output_dir: "${output_root}/${video_name}"
preprocess_dir: ${output_dir}/preprocess
video_path: "${output_dir}/0_input_video.mp4"

# Options
static_cam: False
verbose: False

paths:
  bbx: ${preprocess_dir}/bbx.pt
  bbx_xyxy_video_overlay: ${preprocess_dir}/bbx_xyxy_video_overlay.mp4
  vit_features: ${preprocess_dir}/vit_features.pt
  vitpose: ${preprocess_dir}/vitpose.pt
  vitpose_video_overlay: ${preprocess_dir}/vitpose_video_overlay.mp4
  hmr4d_results: ${output_dir}/hmr4d_results.pt
  incam_video: ${output_dir}/1_incam.mp4
  global_video: ${output_dir}/2_global.mp4
  incam_global_horiz_video: ${output_dir}/${video_name}_3_incam_global_horiz.mp4
  slam: ${preprocess_dir}/slam_results.pt
